//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MDIFormDenemesi
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblDepartman
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblDepartman()
        {
            this.tblDemirbas = new HashSet<tblDemirba>();
            this.tblOdas = new HashSet<tblOda>();
        }
    
        public int departmanID { get; set; }
        public string departmanAdi { get; set; }
        public int fakulteID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblDemirba> tblDemirbas { get; set; }
        public virtual tblFakulte tblFakulte { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblOda> tblOdas { get; set; }
    }
}
