//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MDIFormDenemesi
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblKullanici
    {
        public int kullaniciID { get; set; }
        public Nullable<int> personelID { get; set; }
        public string kullaniciAdi { get; set; }
        public string kullaniciSifre { get; set; }
        public bool yetki { get; set; }
    
        public virtual tblPersonel tblPersonel { get; set; }
    }
}
