//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MDIFormDenemesi
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblOdaDemirba
    {
        public int odaDemirbasAtamaID { get; set; }
        public int odaID { get; set; }
        public int demirbasID { get; set; }
        public Nullable<int> adet { get; set; }
        public int personelID { get; set; }
    
        public virtual tblDemirba tblDemirba { get; set; }
        public virtual tblOda tblOda { get; set; }
        public virtual tblPersonel tblPersonel { get; set; }
    }
}
